import type { LinkPolicy, LinkRelation } from './model.js';

const policies = {
  property_address: {
    relation: 'property_address',
    subjectKinds: ['address'],
    targetKinds: ['property'],
    authoritativeSchemes: ['source-property-id', 'county-parcel-id'],
    normalizedKeyKinds: ['apn', 'address'],
    candidateFields: { address: 4, postalCode: 1 },
    candidateThreshold: 0.82,
    maxCandidatePool: 25,
    requireSameJurisdiction: true,
    requireCompleteEvidence: false,
  },
  property_unit: {
    relation: 'property_unit',
    subjectKinds: ['property-unit', 'address'],
    targetKinds: ['property-unit'],
    authoritativeSchemes: ['assessment-id', 'source-unit-id'],
    normalizedKeyKinds: ['address_unit'],
    candidateFields: { address: 3, unit: 4, postalCode: 1 },
    candidateThreshold: 0.9,
    maxCandidatePool: 15,
    requireSameJurisdiction: true,
    requireCompleteEvidence: false,
  },
  permit_property: {
    relation: 'permit_property',
    subjectKinds: ['permit'],
    targetKinds: ['property', 'property-unit'],
    authoritativeSchemes: ['source-property-id', 'county-parcel-id', 'assessment-id'],
    normalizedKeyKinds: ['address_unit', 'apn', 'address'],
    candidateFields: { address: 4, unit: 3, postalCode: 1 },
    candidateThreshold: 0.84,
    maxCandidatePool: 25,
    requireSameJurisdiction: true,
    requireCompleteEvidence: false,
  },
  permit_contractor: {
    relation: 'permit_contractor',
    subjectKinds: ['permit'],
    targetKinds: ['contractor'],
    authoritativeSchemes: ['cslb-license'],
    normalizedKeyKinds: ['license'],
    candidateFields: { name: 4, address: 2, postalCode: 1 },
    candidateThreshold: 0.88,
    maxCandidatePool: 20,
    requireSameJurisdiction: false,
    requireCompleteEvidence: false,
  },
  contractor_business: {
    relation: 'contractor_business',
    subjectKinds: ['contractor'],
    targetKinds: ['business'],
    authoritativeSchemes: ['ca-sos-entity', 'county-fbn'],
    normalizedKeyKinds: ['entity_number'],
    candidateFields: { name: 4, address: 2, postalCode: 1 },
    candidateThreshold: 0.9,
    maxCandidatePool: 20,
    requireSameJurisdiction: false,
    requireCompleteEvidence: false,
  },
  business_address: {
    relation: 'business_address',
    subjectKinds: ['business'],
    targetKinds: ['address', 'property'],
    authoritativeSchemes: ['source-address-id', 'source-property-id'],
    normalizedKeyKinds: ['address'],
    candidateFields: { address: 4, postalCode: 1 },
    candidateThreshold: 0.86,
    maxCandidatePool: 25,
    requireSameJurisdiction: true,
    requireCompleteEvidence: false,
  },
  ownership_property: {
    relation: 'ownership_property',
    subjectKinds: ['ownership-interest'],
    targetKinds: ['property', 'property-unit'],
    authoritativeSchemes: ['source-property-id', 'assessment-id'],
    normalizedKeyKinds: ['address_unit', 'apn', 'address'],
    candidateFields: { address: 4, unit: 3, postalCode: 1 },
    candidateThreshold: 0.9,
    maxCandidatePool: 20,
    requireSameJurisdiction: true,
    requireCompleteEvidence: true,
  },
  ownership_party: {
    relation: 'ownership_party',
    subjectKinds: ['ownership-interest', 'ownership-event'],
    targetKinds: ['party'],
    authoritativeSchemes: ['source-party-id'],
    normalizedKeyKinds: [],
    candidateFields: { name: 4, address: 2, postalCode: 1 },
    candidateThreshold: 0.94,
    maxCandidatePool: 15,
    requireSameJurisdiction: false,
    requireCompleteEvidence: true,
  },
  transfer_property: {
    relation: 'transfer_property',
    subjectKinds: ['ownership-event'],
    targetKinds: ['property', 'property-unit'],
    authoritativeSchemes: ['source-property-id', 'assessment-id'],
    normalizedKeyKinds: ['address_unit', 'apn', 'address'],
    candidateFields: { address: 4, unit: 3, postalCode: 1 },
    candidateThreshold: 0.9,
    maxCandidatePool: 20,
    requireSameJurisdiction: true,
    requireCompleteEvidence: true,
  },
} as const satisfies Record<LinkRelation, LinkPolicy>;

export function policyFor(relation: LinkRelation): LinkPolicy {
  return policies[relation];
}
