/**
 * Pipeline Run Summary — demo beats 1 & 2.
 *
 * Renders the completed Santa Clara County ingest run from the committed
 * run-summary.json asset (ships with the build): the source list with record
 * counts fetched/loaded and timestamps, records by source, and — prominently —
 * the documented source constraints (the honest gaps: paid Assessor bulk order,
 * single-city permits, paid CA SOS business data).
 *
 * This page is county-independent: it always describes the Santa Clara pipeline
 * run (the deliverable), regardless of which county the query surfaces show.
 */
import runSummary from '../data/santa-clara-run-summary.json';

interface Source {
  name: string;
  description: string;
  url: string;
  records_loaded: number;
}

interface CityCount {
  city: string;
  parcels: number;
}

interface RunSummary {
  generated_by: string;
  county: string;
  state: string;
  output_parquet: string;
  ipfs: {
    dataset_parquet_cid: string;
    properties_sample_root_cid: string;
    pinning_service: string;
  };
  sources: Source[];
  totals: {
    total_parcels: number;
    parcels_with_year_built: number;
    parcels_with_sale_date: number;
    parcels_with_regional_owner: number;
    parcels_with_business_tenant: number;
    parcels_with_permits: number;
    parcels_with_real_cid: number;
    coordinate_coverage: string;
    distinct_cities: number;
    top_cities: CityCount[];
  };
  reconciliation: {
    distinct_owner_entities: number;
    owned_parcels: number;
    portfolio_owners_multi_parcel: number;
    largest_portfolio_parcels: number;
    parcels_held_by_multi_parcel_owners: number;
  };
  constraints: string[];
}

const RUN = runSummary as RunSummary;

function num(n: number): string {
  return n.toLocaleString('en-US');
}

function StatCard({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <div className="border border-slate-200 rounded p-4 bg-white">
      <div className="text-xs uppercase tracking-wide text-slate-500">{label}</div>
      <div className="mt-1 text-2xl font-semibold text-slate-900 tabular-nums">
        {value}
      </div>
      {sub && <div className="mt-1 text-xs text-slate-500">{sub}</div>}
    </div>
  );
}

export default function RunSummary() {
  const maxLoaded = Math.max(1, ...RUN.sources.map((s) => s.records_loaded));
  const maxCity = Math.max(1, ...RUN.totals.top_cities.map((c) => c.parcels));

  return (
    <div className="space-y-6 max-w-4xl">
      <div>
        <h1 className="text-lg font-semibold text-slate-900">
          Pipeline Run Summary — {RUN.county} County, {RUN.state}
        </h1>
        <p className="text-sm text-slate-600 mt-1">
          The completed Oracle pipeline run over Santa Clara County (the county
          containing Palo Alto). Below: the sources ingested, record counts and
          timestamps, and the documented source constraints.
        </p>
      </div>

      {/* Run metadata — all counts are live queries against the served Parquet,
          generated by generate_run_summary.py (never hand-authored). */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <StatCard
          label="Total parcels loaded"
          value={num(RUN.totals.total_parcels)}
          sub={`${num(RUN.totals.distinct_cities)} cities · ${RUN.totals.coordinate_coverage} coords`}
        />
        <StatCard
          label="Assessor sale dates"
          value={num(RUN.totals.parcels_with_sale_date)}
          sub="transfer/deed dates (harvested)"
        />
        <StatCard
          label="Regional owners"
          value={num(RUN.totals.parcels_with_regional_owner)}
          sub="owner mailing outside the county"
        />
        <StatCard
          label="Parcels w/ real IPFS CID"
          value={num(RUN.totals.parcels_with_real_cid)}
          sub="resolvable property_cid"
        />
      </div>

      {/* IPFS artifacts — the pinned, resolvable dataset */}
      <div className="border border-slate-200 rounded bg-white p-4 text-sm space-y-1">
        <div className="font-medium text-slate-800">IPFS dataset artifact (pinned + resolvable)</div>
        <div className="text-xs text-slate-500">
          Dataset Parquet CID:{' '}
          <span className="font-mono text-slate-700 break-all">
            {RUN.ipfs.dataset_parquet_cid}
          </span>
        </div>
        <div className="text-xs text-slate-500">
          Pinning: {RUN.ipfs.pinning_service}
        </div>
      </div>

      {/* Source list */}
      <section className="border border-slate-200 rounded bg-white p-5 space-y-3">
        <div>
          <h2 className="text-base font-semibold text-slate-900">Sources</h2>
          <p className="text-sm text-slate-600 mt-1">
            Each source is a county/city public-data origin. Records fetched vs
            loaded reflects the reconcile/validation gates.
          </p>
        </div>
        <div className="overflow-x-auto">
          <table className="min-w-full text-sm">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-200 text-left">
                <th className="px-3 py-2 font-medium text-slate-600">Source</th>
                <th className="px-3 py-2 font-medium text-slate-600 text-right">
                  Records loaded
                </th>
              </tr>
            </thead>
            <tbody>
              {RUN.sources.map((s) => (
                <tr key={s.name} className="border-b border-slate-100 align-top">
                  <td className="px-3 py-2">
                    <div className="font-mono text-xs text-slate-800">{s.name}</div>
                    <div className="text-xs text-slate-500 max-w-md">
                      {s.description}
                    </div>
                    <a
                      href={s.url}
                      target="_blank"
                      rel="noreferrer"
                      className="text-xs text-slate-500 underline decoration-slate-300 hover:decoration-slate-600 break-all"
                    >
                      {s.url}
                    </a>
                  </td>
                  <td className="px-3 py-2 text-right tabular-nums text-slate-700">
                    {num(s.records_loaded)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* Records by source (visual) */}
      <section className="border border-slate-200 rounded bg-white p-5 space-y-3">
        <h2 className="text-base font-semibold text-slate-900">Records by source</h2>
        <ul className="space-y-2">
          {RUN.sources.map((s) => (
            <li key={s.name} className="flex items-center gap-3 text-sm">
              <span className="w-40 shrink-0 truncate font-mono text-xs text-slate-600">
                {s.name}
              </span>
              <span className="flex-1 h-4 bg-slate-100 rounded-sm overflow-hidden">
                <span
                  className="block h-full bg-slate-500 rounded-sm"
                  style={{ width: `${(s.records_loaded / maxLoaded) * 100}%` }}
                />
              </span>
              <span className="w-24 shrink-0 text-right tabular-nums text-slate-700">
                {num(s.records_loaded)}
              </span>
            </li>
          ))}
        </ul>
        <div className="pt-2">
          <h3 className="text-sm font-medium text-slate-700 mb-2">
            Top cities by parcel count
          </h3>
          <ul className="space-y-1.5">
            {RUN.totals.top_cities.slice(0, 10).map((c) => (
              <li key={c.city} className="flex items-center gap-3 text-sm">
                <span className="w-40 shrink-0 truncate text-slate-600">{c.city}</span>
                <span className="flex-1 h-3.5 bg-slate-100 rounded-sm overflow-hidden">
                  <span
                    className="block h-full bg-slate-400 rounded-sm"
                    style={{ width: `${(c.parcels / maxCity) * 100}%` }}
                  />
                </span>
                <span className="w-20 shrink-0 text-right tabular-nums text-slate-700">
                  {num(c.parcels)}
                </span>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* Entity reconciliation — owners deduped across the parcel set */}
      <section className="border border-slate-200 rounded bg-white p-5 space-y-3">
        <div>
          <h2 className="text-base font-semibold text-slate-900">
            Entity reconciliation
          </h2>
          <p className="text-sm text-slate-600 mt-1">
            Beyond the APN key-join across all 7 sources, owners are reconciled
            across parcels: parcels whose owner mailing address normalizes to the
            same entity are collapsed into one owner, revealing multi-parcel
            (portfolio) owners.
          </p>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          <StatCard
            label="Distinct owner entities"
            value={num(RUN.reconciliation.distinct_owner_entities)}
            sub={`across ${num(RUN.reconciliation.owned_parcels)} owned parcels`}
          />
          <StatCard
            label="Portfolio owners"
            value={num(RUN.reconciliation.portfolio_owners_multi_parcel)}
            sub="hold >1 parcel"
          />
          <StatCard
            label="Largest portfolio"
            value={`${num(RUN.reconciliation.largest_portfolio_parcels)} parcels`}
            sub="single owner entity"
          />
          <StatCard
            label="Parcels in portfolios"
            value={num(RUN.reconciliation.parcels_held_by_multi_parcel_owners)}
            sub="held by multi-parcel owners"
          />
        </div>
      </section>

      {/* Documented source constraints — the honest limitations */}
      <section className="border border-amber-200 bg-amber-50 rounded p-5 space-y-3">
        <div>
          <h2 className="text-base font-semibold text-amber-900">
            Documented source constraints
          </h2>
          <p className="text-sm text-amber-800 mt-1">
            The honest limitations of the v1 Santa Clara ingest — what is a paid
            offline order, single-city, or otherwise not open in California.
          </p>
        </div>
        <ul className="space-y-2">
          {RUN.constraints.map((c, i) => (
            <li
              key={i}
              className="text-sm text-amber-900 bg-white/60 border border-amber-200 rounded px-3 py-2"
            >
              {c}
            </li>
          ))}
        </ul>
      </section>

      <p className="text-xs text-slate-500">
        {RUN.generated_by} · output{' '}
        <span className="font-mono">{RUN.output_parquet}</span>
      </p>
    </div>
  );
}
